### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by manishgonsalves** [ADFCommunity/Home#1]
Has the source code been taken down? We are a team eager to contribute.

**Comment by zivkan** [comment]
No, I wanted to separate the repos so that it's easy to version the build tools separately from the VS extension. And since the two parts will be in separate repos, I created the home repo to have a single place to discuss design issues and bugs. If you go to the ADFCommunity profile page (just click it in the breadcrumb trail near the top of the page), you'll see all the repos in the account.

**Comment by zivkan** [comment]
I just added links to the repo's root readme, so it's easier to find.
